name: Publish Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * Mon

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: repository-string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.repository-string.outputs.lowercase }}/actions-runner:latest

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
